### ISSUE TITLE
Deploying to heroku fails

### ISSUE THREAD

**Issue by mihaibb** [davetron5000/receta#20]
I'm trying to deploy to heroku but `rake assets:precompile` fails because before this I need to run `rake bower:install`.

Is there a way to fix this issue ?

**Comment by davetron5000** [comment]
You should not need to run bower:install during the deploy process—those assets are checked-in to `vendor/assets/bower_components` already.  I just successfully deployed this to Heroku.  Can you paste the error you are getting?

**Comment by manuelvanrijn** [comment]
isn't the whole point of bower that you do not checking your assets in to your own repository?

The problem @mihai-bobina is facing is that by default no node.js nor bower is installed on heroku. To be able to use bower your have add a custom buildpack. Please see: https://coderwall.com/p/6bmygq/heroku-rails-bower from step 11.

you can skip step 13 if you setup bower-rails to fetch before pre-compiling the assets

**Comment by davetron5000** [comment]
I don't think the primary purpose of bower is to prevent vendoring assets.  I think it's just a means to manage your assets and their dependencies.

That said, if you don't want to vendor them, what @manuelvanrijn is suggesting seems like a good place to start.  One danger is that I don't think Bower has the analog of `Gemfile.lock`, so you may run the risk of installing different versions of your assets in production than you have locally.

**Comment by manuelvanrijn** [comment]
Bower-rails generates a `bower.json` file which is used to fetch the dependencies based on their version number, see: https://github.com/davetron5000/receta/blob/master/vendor/assets/bower.json

The only thing here is that it's marked as 'latest' because there is no version number specified in the `Bowerfile`

@davetron5000 not to start a discussion, but aren't we doing the same thing with our Gem's? We don't commit these in our projects right :smile:. Let's say I prefer using bower just like I use rubygems. Great article btw!

**Comment by davetron5000** [comment]
I think the difference is that when you run `bundle install`, even if your `Gemfile` omits version numbers (I.e. wants "latest"), the actual versions installed are written to `Gemfile.lock`.  When you deploy, bundler will use those exact versions, so even if there is an update to all your dependencies, you'll still have the ones you were using locally.

Bower would need that _or_ you'd have to hard-code your versions in your `Bowerfile`.

I would agree vendoring everything isn't ideal, though. I'm not sure how node-based projects do this—do they just vendor everything?
