### ISSUE TITLE
Templates not found when using sprockets version 3.0.0

### ISSUE THREAD

**Issue by JenniferSpry** [davetron5000/receta#23]
The newest version of sprockets does not work with angular-rails-templates (see issue pitr/angular-rails-templates#93).

After batteling the tutorial and getting the version in this repo to run I finally found the source of my problem. Might help other people who do the tutorial :-)

**Comment by sebabouche** [comment]
Thank you! :+1: 

Just to help others (downgrade sprockets to version 2.x):
- update your `Gemfile` with `gem 'sprockets', '~> 2.0'`
- update your gems: `bundle update sprockets`

**Comment by pitr** [comment]
New version of angular-rails-templates v0.1.5 was published that locks sprocket to 2.x Thanks @davetron5000 for PR :+1:

**Comment by davetron5000** [comment]
@pitr awesome, thanks!

I've also added a note to angular-rails.com about the incompatibility, recommending readers on 0.1.4 or below upgrade as well as updating the `Gemfile` on master in this repo.
