### ISSUE TITLE
Browser-based test on view fails

### ISSUE THREAD

**Issue by fasantos** [davetron5000/receta#26]
I'm doing the view recipe part and after all the code fixes the test still fails with the message: 

```
fasantos@ubuntu:~/Sites/MyRecipes$ rspec spec/features/view_spec.rb
F

Failures:

  1) Viewing a recipe view one recipe
     Failure/Error: expect(page).to have_content('Baked Brussel Sprouts')
       expected to find text "Baked Brussel Sprouts" in ""
     # ./spec/features/view_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 23.22 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/features/view_spec.rb:8 # Viewing a recipe view one recipe

Randomized with seed 48691
```

I noticed that mine doesn't have '"Find Recipes Keywords Search"' as in the in book and I don't understand why?
Also after viewing the test, when search is pressed the url changes to: `http://localhost:3000/#/?keywords=baked` but when the recipe is pressed the url changes to: `http://localhost:3000/#/recipes/2?keywords=baked`
shouldn't the "?keywords=baked" be replaced by the recipe url? What I'm I doing wrong? I have revised my code is exactly as in the book.

**Comment by davetron5000** [comment]
These tests are tricky to debug.  If you add `puts page.html` before the expectation, you can see the HTML that was generated.  That might help figure out what was going wrong.  Often, the test expectation fires before the page's DOM has been rewritten by the client-side code.

As to the URLs, angular's `$location` service maintains the query params when you change the url, so the url `#/recipes/2?keywords=baked` **is** the URL to recipe with ID 2, and the controller for that just ignores the query params.

**Comment by fasantos** [comment]
Stupid tipo in the route! After all everything was working as they should but the controller and template were not being loaded because of a tipo in my route. Great tip for debugging, thanks!!!
