### ISSUE TITLE
cannot load such file -- json/ext/parser

### ISSUE THREAD

**Issue by Joeper214** [davetron5000/receta#28]
I am having trouble rendering my json template. Any thoughts of this?
Thanks.

![error](https://cloud.githubusercontent.com/assets/2352389/9188712/3e39c720-401a-11e5-9ede-23fd939af99e.png)

**Comment by davetron5000** [comment]
Can you post your project somewhere?  What OS are you on, what version of Ruby and Rails.

Also if you do `gem list` or `grep json Gemfile.lock` what does it show you?

**Comment by Joeper214** [comment]
**\* LOCAL GEMS ***

actionmailer (4.2.3, 4.2.1)
actionpack (4.2.3, 4.2.1)
actionview (4.2.3, 4.2.1)
activejob (4.2.3, 4.2.1)
activemodel (4.2.3, 4.2.1)
activerecord (4.2.3, 4.2.1)
activesupport (4.2.3, 4.2.1)
angular-rails-templates (0.2.0, 0.1.4)
angularjs-rails-resource (2.0.0)
arel (6.0.3, 6.0.2, 6.0.0)
bigdecimal (1.2.7, 1.2.0)
binding_of_caller (0.7.2)
bower-rails (0.10.0, 0.9.2)
builder (3.2.2)
bundler (1.10.6)
byebug (5.0.0)
capybara (2.4.4)
childprocess (0.5.6)
coffee-rails (4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
columnize (0.9.0)
database_cleaner (1.4.1)
debug_inspector (0.0.2)
diff-lcs (1.2.5)
erubis (2.7.0)
execjs (2.5.2)
factory_girl (4.5.0)
factory_girl_rails (4.5.0)
ffi (1.9.10, 1.9.8)
foreman (0.78.0)
globalid (0.3.6, 0.3.5)
hike (1.2.3)
i18n (0.7.0)
io-console (0.4.2)
jbuilder (2.3.1, 2.2.16, 1.5.3)
jquery-rails (4.0.4, 4.0.3)
json (1.8.3, 1.8.2, 1.7.7)
json_builder (3.1.7)
libv8 (3.16.14.11 x86_64-linux)
loofah (2.0.2)
mail (2.6.3)
mime-types (2.6.1, 2.5)
mini_portile (0.6.2)
minitest (5.7.0, 5.6.1)
multi_json (1.11.2, 1.11.0)
mysql (2.9.1)
mysql2 (0.3.19)
nokogiri (1.6.6.2)
phantomjs (1.9.8.0)
postgres-pr (0.7.0)
psych (2.0.0)
rack (1.6.4, 1.6.1)
rack-test (0.6.3)
rails (4.2.3, 4.2.1)
rails-assets-angular (1.4.3)
rails-assets-angular-resource (1.4.3)
rails-assets-angular-route (1.4.3)
rails-assets-bootstrap (3.3.5)
rails-assets-jquery (2.1.4)
rails-assets-leaflet (0.7.3)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.6)
rails-html-sanitizer (1.0.2)
rails_12factor (0.0.3)
rails_serve_static_assets (0.0.4)
rails_stdout_logging (0.0.3)
railties (4.2.3, 4.2.1)
rake (10.4.2)
rdoc (4.2.0, 4.0.0)
ref (2.0.0)
responders (2.1.0)
rspec (3.2.0)
rspec-collection_matchers (1.1.2)
rspec-core (3.2.3, 2.99.2)
rspec-expectations (3.2.1, 2.99.2)
rspec-mocks (3.2.1, 2.99.4)
rspec-rails (3.2.1, 2.99.0)
rspec-support (3.2.2)
rubygems-update (2.4.8)
rubyzip (1.1.7)
sass (3.4.16, 3.4.13, 3.2.19)
sass-rails (5.0.3)
sdoc (0.4.1)
selenium-webdriver (2.47.1, 2.45.0)
spring (1.3.6)
sprockets (3.2.0, 2.12.4, 2.12.3)
sprockets-rails (2.3.2, 2.3.1)
sqlite3 (1.3.10)
teaspoon (1.0.2, 0.7.9)
teaspoon-jasmine (2.2.0)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
turbolinks (2.5.3)
tzinfo (1.2.2)
uglifier (2.7.1)
web-console (2.2.1)
websocket (1.2.2)
xpath (2.0.0)

**Comment by Joeper214** [comment]
Also the project code is here. https://github.com/Joeper214/receta.git .. Thanks!

**Comment by davetron5000** [comment]
I can't recreate your problem.  It seems to be rendering JSON for me.  There's two sets of templates in there—I'm not sure what the `.json_builder` files are for.
